---
ocp_version: 4.7
rhcos_version: 4.7.0
img_arch: x86_64
vm_import_bucket_name: rhcos-vmdk-import
user_home_dir: "{{ lookup('env', 'HOME') }}"
cloud_region: "{{ lookup('ini', 'region section=default file={{ user_home_dir }}/.aws/config') }}"
cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ user_home_dir }}/.aws/credentials') }}"
cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ user_home_dir }}/.aws/credentials') }}"
