---
- name: RHCOS AWS AMI | VMDK Management
  include_tasks: rhcos-vmdk-s3.yml

- name: RHCOS AWS AMI | Create AMI
  include_tasks: rhcos-ami-create.yml

- name: RHCOS AWS AMI | Cleanup local files
  include_tasks: cleanup.yml

