#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: Place OpenShift RHCOS Image | rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk.gz
  get_url:
    url: 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_version }}/latest/rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk.gz'
    dest: '/tmp/rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk.gz'
    mode: 0775

- name: 'Create AWS S3 Bucket: {{ vm_import_bucket_name }}'
  aws_s3:
    bucket: '{{ vm_import_bucket_name }}'
    region: '{{ cloud_region }}'
    mode: create
    aws_access_key: '{{ cloud_key_id_special }}'
    aws_secret_key: '{{ cloud_key_secret_special }}'
  ignore_errors: True

- name: Uncompress RHCOS VMDK
  shell: gunzip /tmp/rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk.gz

- name: 'Push RHCOS VMDK to AWS S3 Bucket: {{ vm_import_bucket_name }}' 
  aws_s3:
    mode: put
    bucket: '{{ vm_import_bucket_name }}'
    region: '{{ cloud_region }}'
    object: 'rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk'
    src: /tmp/rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk
    aws_access_key: '{{ cloud_key_id_special }}'
    aws_secret_key: '{{ cloud_key_secret_special }}'

- name: Delete RHCOS VMDK
  file: 
    path: /tmp/rhcos-{{ rhcos_version }}-{{ img_arch }}-aws.{{ img_arch }}.vmdk
    state: absent
