- name: RHCOS AWS AMI | Set Random ID for S3 bucket to avoid conflict
  set_fact:
    vm_import_bucket_name: "{{ import_bucket_name }}-{{ 10000 | random }}"

- name: RHCOS AWS AMI | Download OpenShift RHCOS Image | rhcos-{{ rhcos_version }}-{{ rhcos_arch }}
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/{{ rhcos_arch }}/dependencies/rhcos/{{ ocp_version }}/{{ rhcos_version }}/rhcos-aws.{{ rhcos_arch }}.vmdk.gz"
    dest: '/tmp/rhcos-aws.{{ rhcos_arch }}.vmdk.gz'
    mode: 0644

- name: RHCOS AWS AMI | Unzip VMDK
  command: "gunzip /tmp/rhcos-aws.{{ rhcos_arch }}.vmdk.gz" 
  args:
    creates: "/tmp/rhcos-aws.{{ rhcos_arch }}.vmdk"
   
- name: 'RHCOS AWS AMI | Create AWS S3 Bucket: {{ vm_import_bucket_name }}'
  aws_s3:
    bucket: '{{ vm_import_bucket_name }}'
    region: '{{ cloud_region }}'
    mode: create
    aws_access_key: '{{ cloud_key_id_special }}'
    aws_secret_key: '{{ cloud_key_secret_special }}'
  ignore_errors: True

- name: 'RHCOS AWS AMI | Push RHCOS VMDK to AWS S3 Bucket: {{ vm_import_bucket_name }}' 
  aws_s3:
    mode: put
    bucket: '{{ vm_import_bucket_name }}'
    region: '{{ cloud_region }}'
    object: 'rhcos-{{ rhcos_version }}-{{ rhcos_arch }}-aws.{{ rhcos_arch }}.vmdk'
    src: /tmp/rhcos-aws.{{ rhcos_arch }}.vmdk
    aws_access_key: '{{ cloud_key_id_special }}'
    aws_secret_key: '{{ cloud_key_secret_special }}'
